### ISSUE TITLE
Is publishing to the play store on your roadmap?

### ISSUE THREAD

**Issue by CirclesCenter** [tatsutron/mistercon#7]
I really think you're onto something here with this app. I think more people should see it and use it.

**Comment by tatsutron** [comment]
Thanks for the question!

We've definitely given it some thought here and there. There's a recurring cost since Google wants $25 per year to include apps in their store. That's not necessarily a deal breaker, but it's one of the reasons we've hesitated it so far.

At the end of the day we'd love to have the app on the store. I guess the question in our minds is whether people who otherwise would not have discovered the app would discover it if it were available there.

**Comment by CirclesCenter** [comment]
Well while I'm generally speaking broke due to disability... *but* I do have a google play balance of $20 for some random reason and I'd like to see your app on the store. I think it'll make it more accessible and you'll get more users.

Wherever you take the project I'm glad you've made this app. It makes the MiSTer much more friendly.

I'm following the project so I should get a notification. I'm a total github noob so apologies if I've been too forward or take a while to reply.

**Comment by NanoDrivee** [comment]
I'm interested in seeing the app published elsewhere for the purposes of auto updating. F-Droid would be perfect for this if developer fees are an issue, maybe look into publishing there.

**Comment by tatsutron** [comment]
Thanks for the feedback @CirclesCenter and @NanoDrivee -- I hadn't considered the updating side of things, and I would definitely like to make that as convenient as possible. I think we will go ahead and get this on the store in a future public release.
